### ISSUE TITLE
Flytte fra internal til public repo

### ISSUE THREAD

**Issue by MikAoJk** [navikt/melosys-web#1405]
Hei!
Lurte på om det var noe spesiell grunn til at repoet er internal.
https://github.com/navikt/offentlig

**Comment by MikAoJk** [comment]
@navikt/teammelosys

**Comment by frans-a** [comment]
Se svar her https://github.com/navikt/melosys-dokgen/issues/144#issuecomment-1061590457
Å åpne issues i repoer fra samme team i stedet for å kommunisere med teamet direkte er ganske ineffektiv @MikAoJk
